### ISSUE TITLE
Support Fronius Inverter

### ISSUE THREAD

**Issue by california444** [hendrikmuhs/lambda-heatpump-modbus-tcp#1]
Hi @hendrikmuhs,
thanks for sharing your script.
Are you open for a PR to also support Fronius Inverter as "source"?
From the code base it looks like that this is intended.
I have a Fronius inverter and smart meter and could add a new source-type + logic for this.

**Comment by hendrikmuhs** [comment]
sounds good. I happily merge your PR.

**Comment by california444** [comment]
Sry, it took a little bit longer than expected....
I started to create a draft PR and will close this issue here.... 
I'm still waiting for my Lambda heatpump, so I cannot fully prove it is working....
